name: Push DockerHub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tianheg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: local_version
        run: |
          LOCAL_VERSION=$(sed '3q;d' Dockerfile | cut -c18-24)
          echo "::set-output name=VERSION::$LOCAL_VERSION"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tianheg/hugo:latest,tianheg/hugo:${{ steps.local_version.outputs.VERSION }}
